### PR TITLE
update solidity version to ^0.7.0

### PR DESCRIPTION
**Pull request by axchu**
### Fixes
- Fixes https://github.com/ethereum-optimism/roadmap/issues/266

## Contributing Agreement

- [x] I have read and understood the [Optimism Contributing Guide and Code of Conduct](https://github.com/ethereum-optimism/optimism-monorepo/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

### CODE REVIEW

**Review by kfichter — DISMISSED** [review]
LGTM. Just noting here that `>0.6.0 <0.8.0` will be necessary for any `// +build ovm` contracts.

**Comment by ben-chain** [comment]
Actually, just realized we didn't bump version in the buidler config -- can we bump to latest so the more recent version actually gets used?

**Comment by ben-chain** [comment]
additional requested update in addition to the above comment -- can we actually make the version for all *interfaces* still be `>0.5.0 <0.8.0` ? This allows people on different versions of solidity to still import our interfaces.

**Comment by axchu** [comment]
> Actually, just realized we didn't bump version in the buidler config -- can we bump to latest so the more recent version actually gets used?

looks like the version is 0.7.4 at the moment, does that need to be bumped?

**Comment by ben-chain** [comment]
> looks like the version is 0.7.4 at the moment, does that need to be bumped?

Yes, let's bump to whatever is the latest `0.7` release.

**Comment by axchu** [comment]
> > looks like the version is 0.7.4 at the moment, does that need to be bumped?
> 
> Yes, let's bump to whatever is the latest `0.7` release.

Latest is 0.7.6 but that breaks these basic tests:
```OVM_ExecutionManager Test: Basic tests for CREATEEOA
       should execute: ovmCREATEEOA, ovmEXTCODESIZE(CREATED):
       Error: Transaction reverted for an unrecognized reason. Please report this to help us improve Buidler.
      at OVM_ExecutionManager._decodeRevertData (contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol:1429)
      at OVM_ExecutionManager._decodeRevertData (contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol:1429)
      at OVM_ExecutionManager._handleExternalInteraction (contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol:992)
      at OVM_ExecutionManager._callContract (contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol:929)
      at OVM_ExecutionManager.ovmCALL (contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol:539)
      at OVM_ExecutionManager.ovmCALL (contracts/optimistic-ethereum/OVM/execution/OVM_ExecutionManager.sol:521)
      at process._tickCallback (internal/process/next_tick.js:68:7)```

**Review by ben-chain — APPROVED** [review]
LGTM!  Can you change the title/commit message to specify 0.7.6 in particular when you merge?  Thanks!

**Pull request merged**
